#version: "3.9"
services:
  mysql:
    # use latest mysql 8.0 image
    image: "mysql:8.0"
    restart: always
    # custom name for container
    container_name: mysql
    # connect container port 3306 to host port 3306
    ports:
      - "3306:3306"
    # set environment variables for container
    environment:
      # set password for MySQL root user to 'pass'
      - MYSQL_ROOT_PASSWORD=pass
      # create a database 'todo' on container start, if it does not exist
      - MYSQL_DATABASE=todo
    expose:
      # Opens port 3306 on the container
      - "3306"
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: